import { existsSync, copyFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve } from "node:path";
import { randomBytes } from "node:crypto";
import { generateKeyPair, uint8ToBase64 } from "@binalyze/notar";

const ROOT = resolve(import.meta.dirname, "..");
const KEYS_JSON = resolve(ROOT, "packages/web/src/public/.well-known/notar-keys.json");
const ENV_EXAMPLE = resolve(ROOT, ".env.example");
const ENV_DEV = resolve(ROOT, ".env.dev");
const ENV_PROD = resolve(ROOT, ".env.prod");

const force = process.argv.includes("--force");

let step = 0;
function log(msg: string) { console.log(`  ✅ Step ${++step}: ${msg}`); }
function info(msg: string) { console.log(`            ${msg}`); }

async function main() {
  console.log("\n  Notar Setup\n");

  // Early exit if everything is already set up
  const allExist = existsSync(ENV_DEV) && existsSync(ENV_PROD) && existsSync(KEYS_JSON);
  if (!force && allExist) {
    log("Checking .env.dev — Already exists");
    log("Checking .env.prod — Already exists");
    log("Checking notar-keys.json — Already exists");
    console.log("\n  ✅ All set! Use --force to regenerate.\n");
    console.log("  Next steps:");
    console.log("    pnpm dev       Start the dev server");
    console.log("    pnpm deploy    Build and deploy to Cloudflare\n");
    return;
  }

  // Step: Copy .env.example → .env.dev (exact copy, keeps sample keys)
  copyFileSync(ENV_EXAMPLE, ENV_DEV);
  log("Copying .env.example → .env.dev — Done");

  // Step: Generate fresh keys for production
  log("Generating Ed25519 key pair for production...");
  const { publicKey, privateKey } = await generateKeyPair();
  const pubB64 = uint8ToBase64(publicKey);
  const privB64 = uint8ToBase64(privateKey);
  const keyId = `key_${randomBytes(6).toString("hex")}`;
  info(`Key ID:      ${keyId}`);
  info(`Public Key:  ${pubB64}`);
  info(`Private Key: ${privB64}`);

  // Step: Write .env.prod with generated keys
  const prodContent = [
    "# Generated by pnpm setup — do not commit.",
    "BUILD_MODE=production",
    `NOTAR_PUBLIC_KEY=${pubB64}`,
    `NOTAR_PRIVATE_KEY=${privB64}`,
    `NOTAR_KEY_ID=${keyId}`,
    "",
  ].join("\n");
  writeFileSync(ENV_PROD, prodContent);
  log("Writing .env.prod — Done");

  // Step: Write notar-keys.json with the production public key
  const expires = new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString();
  mkdirSync(resolve(ROOT, "packages/web/src/public/.well-known"), { recursive: true });
  const keysJson = JSON.stringify({
    keys: [{
      keyId,
      algorithm: "ed25519",
      publicKey: pubB64,
      expires,
      revoked: false,
    }],
  }, null, 2) + "\n";
  writeFileSync(KEYS_JSON, keysJson);
  log("Saving packages/web/src/public/.well-known/notar-keys.json — Done");

  console.log("\n  ✅ Setup complete!\n");
  console.log("  Next steps:");
  console.log("    pnpm dev       Start the dev server");
  console.log("    pnpm deploy    Build and deploy to Cloudflare\n");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
